name: Bedrock Resource Pack Compressor
author: famima65536
description: make .mcpack file automatically with simple config.
inputs:
  source:
    description: >
      directory to be compressed as .mcpack.
    default: ''
    type: string
  destination:
    description: >
      directory where the mcpacked resource pack will be put.
    type: string
  pack-name:
    description: 'resource pack name: pack-name.mcpack'
    required: true
    type: string
  minify: 
    description: determine whether to minify json file
    required: false
    type: bool
    default: true

runs:
  using: composite
  steps:
    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: install dependencies
      shell: bash
      run: pip install -r $GITHUB_ACTION_PATH/requirements.txt
    - name: compress pack
      run: python $GITHUB_ACTION_PATH/src/compressor.py
      shell: bash
      env: 
        PACK_SRC: ${{ inputs.source }}
        PACK_DEST: ${{ inputs.destination }}
        PACK_NAME: ${{ inputs.pack-name }}
        MINIFY: ${{ inputs.minify }}